# -*- mode: ruby -*-
# vi: set ft=ruby :
# ==================================================================
# Vagrant configuration for vagrant-java on Ubuntu 14.4
# ==================================================================
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  # Forward ports
  config.vm.network :forwarded_port, guest: 8080, host: 8080

  # Share the working dir - host, guest
  config.vm.synced_folder "drop", "/vagrant"

  config.vm.provision "shell", inline: "apt-get update --fix-missing"

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "cookbooks"
    
    chef.add_recipe "git"
    chef.add_recipe "java"
    chef.add_recipe "java_se"
    chef.add_recipe "groovy"
    chef.add_recipe "gradle"
    chef.add_recipe "squid"
  end
end


